image: /home/hsuhanjaya/Richard/unitree_ws/src/go2_robot_sdk/config/qrc_iros.png
resolution: 0.05
origin: [5.375000095367431, 0.7750000119209289, 0.0000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196
